# Generated by Django 3.2.13 on 2023-09-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('jogo_referencia', models.CharField(blank=True, max_length=50)),
                ('habilidade_importante', models.CharField(blank=True, max_length=50)),
                ('dentro_de_BTD6', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.CharField(max_length=300)),
                ('dica', models.CharField(blank=True, max_length=200)),
                ('estilo', models.CharField(blank=True, max_length=100)),
                ('autor', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('dano', models.IntegerField()),
                ('tipo_de_dano', models.CharField(choices=[('N/A', 'Normal'), ('Purple', 'Plasma'), ('Black', 'Explosão'), ('Purple, Lead', 'Energia'), ('Lead, Frozen', 'Afiado'), ('All', 'Passivo')], max_length=15)),
                ('alcance', models.IntegerField()),
                ('perfuracao', models.IntegerField()),
                ('propriedades_especiais', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
