# Generated by Django 3.2.13 on 2023-09-16 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBTD6introduction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia',
            name='autor',
        ),
    ]
