# Generated by Django 3.2.13 on 2023-09-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBTD6introduction', '0002_remove_historia_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='autor',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
