# Generated by Django 3.2.13 on 2023-09-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBTD6introduction', '0003_historia_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='titulo',
            field=models.CharField(max_length=500),
        ),
    ]
